name: gestao_financeira_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
  

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  flutter_money_formatter: ^0.8.3
  #moneytextformfield: ^0.3.5+1
  flutter_masked_text: ^0.8.0
  flutter_datetime_picker: ^1.4.0
  direct_select_flutter: ^1.0.6
  datetime_picker_formfield: ^1.0.0
  charts_flutter: ^0.9.0
  fl_chart: ^0.10.0
  sembast: ^2.4.7+6
  path_provider: ^1.6.11
  flutter_bloc: ^0.9.1
  flutter_local_notifications: ^1.4.4+1
  url_launcher: ^5.4.2
  http:
  html: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  assets:
    - assets/logo_2_asset.jpg
    - assets/logo_1.png


  uses-material-design: true
